export const ARIA_LABELS = {
  PASSWORD_VISIBLE_TOGGLE: "パスワードの表示切り替え",
  YEAR_SELECTOR_PREV: "前の年へ",
  YEAR_SELECTOR_NEXT: "次の年へ",
  MONTH_SELECTOR_PREV: "前の月へ",
  MONTH_SELECTOR_NEXT: "次の月へ",
  DATE_PICKER_INPUT: "日付を選択",
  DATE_PICKER_CANCEL: "日付の選択を解除",
  RANGE_DATE_PICKER_INPUT: "日付の範囲を選択",
  RANGE_DATE_PICKER_SELECT_BOX_INPUT: "日付の種類を選択",
  RANGE_DATE_PICKER_CANCEL: "日付の範囲の選択を解除",
  PAGINATION: "ページネーション",
  PAGINATION_PREV: "前のページへ",
  PAGINATION_NEXT: "次のページへ",
} as const;
