<template>
  <WizVStack>
    <WizAnchor
      to="https://wizleap.co.jp"
      :icon="WizIOpenInNew"
      icon-position="right"
      color="gray.700"
      font-size="sm"
      open-in-new-tab
      nowrap
    >
      会社概要
    </WizAnchor>
    <WizAnchor
      to="https://wizleap.co.jp/services/"
      :icon="WizIOpenInNew"
      icon-position="right"
      color="gray.700"
      font-size="sm"
      open-in-new-tab
      nowrap
    >
      サービス
    </WizAnchor>
    <WizAnchor
      to="https://wizleap.co.jp/news/"
      :icon="WizIOpenInNew"
      icon-position="right"
      color="gray.700"
      font-size="sm"
      open-in-new-tab
      nowrap
    >
      ニュース
    </WizAnchor>
  </WizVStack>
</template>

<script setup lang="ts">
import { WizAnchor, WizVStack, WizIOpenInNew } from "@wizleap-inc/wiz-ui-next";
</script>
