name: Prepare Node.js Environment
description: Prepare Node.js environment for the job, this is a composite action for reusability
inputs:
  node-version:
    description: "Node.js version to use"
    required: false
    default: "16.x"
  runs-on:
    description: "Operating system to use"
    required: false
    default: "ubuntu-20.04"
  node-auth-token:
    description: "Node auth token to publish to npm"
    required: true
    default: ""

runs:
  using: "Composite"
  steps:
    - name: Use Node.js ${{ inputs.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ inputs.node-version }}
        registry-url: "https://registry.npmjs.org"
        scope: "@wizleap-inc"
        always-auth: true
      env:
        NODE_AUTH_TOKEN: ${{ inputs.node-auth-token }}

    - uses: actions/cache@v2
      with:
        path: '**/node_modules'
        key: ${{ runner.os }}-modules-${{ hashFiles('**/yarn.lock') }}

    - name: Install dependencies
      shell: bash
      run: yarn --frozen-lockfile
