name: Bundle Analyze All libraries

on: [pull_request]

jobs:
  analyze:
    runs-on: ubuntu-20.04

    strategy:
      matrix:
        node-version: [20.x]

    steps:
      - uses: actions/checkout@v4

      # - name: Enable Corepack
      #   run: corepack enable

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}

      - name: 📥 Monorepo install
        uses: ./.github/composite/prepare_node

      - uses: preactjs/compressed-size-action@v2
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          build-script: build
          pattern: "./packages/{wiz-ui,wiz-ui-next,wiz-ui-react}/dist/{wiz-ui.es.js,wiz-ui.umd.js,style.css}"
