name: Check Wiz-UI Component Name

on: push

jobs:
  lint:
    runs-on: ubuntu-20.04

    steps:
      - name: checkout
        uses: actions/checkout@v2

      - name: ls
        run: ls -la

      - name: pwd
        run: pwd

      - name: check undefined component name count
        run: |
          echo ::set-output name=undefined_component_name_count::$(grep -Lir 'defineOptions' ./packages/**/*.vue | wc -l)

      - name: check undefined component name
        if: ${{ steps.undefined_component_name_count.outputs.undefined_component_name_count > 0 }}
        run: |
          echo "There are undefined component name in the following files:"
          grep -Lir 'defineOptions' packages/**/*.vue

      - name: Fail if there are undefined component name
        if: ${{ steps.undefined_component_name_count.outputs.undefined_component_name_count > 0 }}
        run: exit 1
