name: Publish Wiz-UI library

env:
  YARN_CACHE_FOLDER: .cache/yarn

on:
  push:
    branches:
      - main
    tags:
      - "!*"

jobs:
  publish:
    runs-on: ubuntu-20.04

    strategy:
      matrix:
        node-version: [16.x]

    steps:
      - name: checkout
        uses: actions/checkout@v2

      - uses: ./.github/composite/prepare_node
        with:
          node-version: ${{ matrix.node-version }}
          runs-on: ${{ matrix.runs-on }}
          node-auth-token: ${{ secrets.NODE_AUTH_TOKEN }}
          yarn-cache-folder: ${{ env.YARN_CACHE_FOLDER }}

      - name: build
        run: yarn build:lib

      - name: Create Release Pull Request or Publish to npm
        id: changesets
        uses: changesets/action@v1
        with:
          publish: yarn release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NODE_AUTH_TOKEN: ${{ secrets.NODE_AUTH_TOKEN }}
