name: Visual Regression Test Wiz-UI library

on: [push]

env:
  REG_NOTICE_CLIENT_ID: ${{ secrets.REG_NOTICE_CLIENT_ID }}
  AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
  AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

jobs:
  build:
    runs-on: ubuntu-20.04

    strategy:
      matrix:
        node-version: [16.x]

    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}

      - name: 📥 Monorepo install
        uses: ./.github/composite/prepare_node
      - name: Install fonts
        run: sudo apt-get install fonts-ipafont-gothic fonts-ipafont-mincho

      - name: workaround for detached HEAD
        run: |
          git checkout ${GITHUB_REF#refs/heads/} || git checkout -b ${GITHUB_REF#refs/heads/} && git pull

      - name: run storybook generate
        run: yarn workspace @wizleap-inc/wiz-ui build:storybook

      - name: run storycap
        run: yarn workspace @wizleap-inc/wiz-ui ci:storycap

      - name: run reg-suit
        run: yarn workspace @wizleap-inc/wiz-ui ci:vrt
